---
language: node_js

node_js:
  - "10.15.1"

cache:
  yarn: true
  directories:
      - .npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install: true

script:
  - yarn test
